initial skeleton
dhyon/prototype pull request #25
Opened 2021-10-06 14:54 UTC by muhdmud

2021-10-06 15:15 UTC, muhdmud commented
@dhyon @samullman initial commit, have a look let me know how it can be better(or good enough for the hackathon) or if we have proper social links

2021-10-06 18:21 UTC, samullman submitted a review, later dismissed

2021-10-06 20:10 UTC, dhyon requested changes
Looks good @muhdmud

Can you reopen this PR to point against main? We're ditching staging now

2021-10-07 01:01 UTC, muhdmud commented
Sure, on it. Thanks @samullman @dhyon

2021-10-07 01:33 UTC, closed without merging